const API='/api';
let players=[],subs=[],currentPlayer=null,chart;
let token=localStorage.getItem('ah_token')||'';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const formatDate=v=>{if(!v)return '—';const s=String(v);const d=s.includes('T')?s.split('T')[0]:s.split(' ')[0];const parts=d.split('-');return parts.length===3?`${parts[2]}-${parts[1]}-${parts[0]}`:s};
const money=v=>`${Number(v??0).toLocaleString('en-US')} JD`;
const sportIcons={Football:'⚽',Basketball:'🏀',Swimming:'🏊',Volleyball:'🏐',Taekwondo:'🥋'};
const sportIcon=s=>sportIcons[s]||'🏅';
const badge=s=>`<span class="badge ${s==='Active'?'active':s==='Expiring Soon'?'expiring':s==='Expired'?'expired':'pending'}">${esc(s)}</span>`;
const paymentBadge=s=>`<span class="badge ${s==='Paid'?'active':s==='Overdue'?'expired':'pending'}">${esc(s)}</span>`;
const initials=p=>(p.first_name?.[0]||'')+(p.last_name?.[0]||'');
const avatar=p=>p.photo_url?`<img src="${esc(p.photo_url)}" alt="${esc(p.first_name+' '+p.last_name)}">`:initials(p);
function readPhoto(file){return new Promise((resolve,reject)=>{if(!file||!file.size)return resolve(null);if(!file.type.startsWith('image/'))return reject(Error('Please choose an image file.'));const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=600;const scale=Math.min(1,max/Math.max(img.width,img.height));const w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',0.82));};img.onerror=()=>reject(Error('Could not read the image.'));img.src=reader.result;};reader.onerror=()=>reject(Error('Could not read the image.'));reader.readAsDataURL(file);});}
async function api(type,opts={}){let u=API+'/data?type='+encodeURIComponent(type)+(opts.query||'');let headers=opts.body?{'Content-Type':'application/json'}:{};if(token)headers.Authorization='Bearer '+token;let r=await fetch(u,{method:opts.method||'GET',headers,body:opts.body?JSON.stringify(opts.body):undefined});let j=await r.json().catch(()=>({}));if(r.status===401){logout();throw Error(j.error||'Please sign in to continue')}if(!r.ok)throw Error(j.error||'Request failed');return j}

function showApp(){document.getElementById('loginScreen').style.display='none';document.getElementById('appRoot').style.display='';}
function showLogin(msg){document.getElementById('appRoot').style.display='none';document.getElementById('loginScreen').style.display='';const err=document.getElementById('loginError');if(err)err.textContent=msg||'';document.getElementById('loginPassword').value='';document.getElementById('loginUsername').focus();}
function logout(){token='';localStorage.removeItem('ah_token');showLogin()}
async function login(username,password){const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Sign in failed');token=j.token;localStorage.setItem('ah_token',token)}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=document.getElementById('loginSubmit');const err=document.getElementById('loginError');err.textContent='';btn.disabled=true;btn.textContent='Signing in…';try{await login(document.getElementById('loginUsername').value.trim(),document.getElementById('loginPassword').value);showApp();boot()}catch(e){err.textContent=e.message}finally{btn.disabled=false;btn.textContent='Sign in'}});
document.getElementById('logoutBtn').addEventListener('click',logout);

function showPage(id){
 document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');
 document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));
 const titles={dashboard:['Overview','Good afternoon 👋'],players:['Player Management','Your academy roster'],subscriptions:['Subscriptions','Plans, payments and renewals'],attendance:['Attendance','Track who is on the pitch'],notifications:['Notifications','Renewals and academy reminders'],settings:['Settings','Academy configuration'],profile:['Player Profile','Player details and history']};
 document.getElementById('eyebrow').textContent=titles[id][0];document.getElementById('pageTitle').textContent=titles[id][1];
 if(id==='dashboard')loadDashboard();if(id==='players')loadPlayers();if(id==='subscriptions')loadSubs();
 if(id==='attendance'){document.getElementById('attDate').value ||= new Date().toISOString().slice(0,10);loadAttendance()}
 if(id==='notifications')loadNotifications();if(id==='settings')loadSettings();
}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));

async function loadDashboard(){
 try{
  let d=await api('dashboard');mPlayers.textContent=d.totalPlayers;mActive.textContent=d.activeSubscriptions;mExpiring.textContent=d.expiringSoon;mExpired.textContent=d.expiredSubscriptions;
  attPresent.textContent=d.todayAttendance.present;attAbsent.textContent=d.todayAttendance.absent;let total=(+d.todayAttendance.present||0)+(+d.todayAttendance.absent||0);attPct.textContent=total?Math.round(d.todayAttendance.present/total*100)+'%':'—';
  activity.innerHTML=d.activity.length?d.activity.map(x=>`<div class="activityrow"><i class="dot"></i><div><b>${esc(x.action)}</b><p>${esc(x.detail)} · ${formatDate(x.created_at)}</p></div></div>`).join(''):'<div class="empty">No activity yet</div>';
  let s=await api('subscriptions');let soon=s.subscriptions.filter(x=>x.subscription_status!=='Active').slice(0,3);
  renewalMini.innerHTML=soon.length?soon.map(x=>`<div style="display:flex;justify-content:space-between;align-items:center;padding:9px 0;border-bottom:1px solid var(--line)"><div><b style="font-size:12px">${esc(x.first_name+' '+x.last_name)}</b><div class="sub">Expires ${esc(formatDate(x.expiry_date))}</div></div>${badge(x.subscription_status)}</div>`).join(''):'<div class="empty">All memberships are up to date 🎉</div>';
  drawChart(d.revenueTrend||[]);
 }catch(e){toast(e.message)}
}
function drawChart(trend){let ctx=document.getElementById('revenueChart');if(chart)chart.destroy();chart=new Chart(ctx,{type:'line',data:{labels:trend.map(x=>x.label),datasets:[{label:'Revenue',data:trend.map(x=>Number(x.total)),tension:.35,fill:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{callback:v=>money(v)}},x:{grid:{display:false}}}}})}

async function loadPlayers(){try{let d=await api('players',{query:'&search='+encodeURIComponent(playerSearch.value)});players=d.players.filter(p=>(!sportFilter.value||p.sport===sportFilter.value)&&(!statusFilter.value||p.status===statusFilter.value));playersBody.innerHTML=players.map(p=>`<tr><td><div class="person"><div class="mini">${avatar(p)}</div><div><b>${esc(p.first_name+' '+p.last_name)}</b><div class="sub">${esc(p.parent_name||'No guardian')}</div></div></div></td><td>${p.age} · ${esc(p.gender)}</td><td>${sportIcon(p.sport)} ${esc(p.sport)}</td><td>${esc(p.category)}</td><td>${p.subscription?badge(p.subscription.subscription_status):badge('Pending')}</td><td>${badge(p.status)}</td><td><div class="actions"><button class="iconbtn" onclick="viewPlayer(${p.id})">View</button><button class="iconbtn" onclick="editPlayer(${p.id})">Edit</button><button class="iconbtn" onclick="deletePlayer(${p.id})">×</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No players match your search.</td></tr>'}catch(e){toast(e.message)}}
async function viewPlayer(id){try{let d=await api('player',{query:'&id='+id});currentPlayer=d;showPage('profile');let p=d.player;profileContent.innerHTML=`<div class="profilehead"><div class="profilepic">${avatar(p)}</div><div class="profilemeta"><h2>${esc(p.first_name+' '+p.last_name)}</h2><p>${sportIcon(p.sport)} ${esc(p.sport)} · ${esc(p.category)} · Coach ${esc(p.coach||'—')}</p><div>${badge(p.status)}</div></div><div style="margin-left:auto">${d.subscriptions[0]?badge(d.subscriptions[0].subscription_status):''}</div></div><div class="profilegrid"><div class="card"><div class="sectionhead"><h3>Personal information</h3></div><div class="info"><div><label>Date of birth</label><div>${esc(formatDate(p.date_of_birth))}</div></div><div><label>Age / Gender</label><div>${p.age} / ${esc(p.gender)}</div></div><div><label>Phone</label><div>${esc(p.phone||'—')}</div></div><div><label>Join date</label><div>${esc(formatDate(p.join_date))}</div></div><div><label>Parent / Guardian</label><div>${esc(p.parent_name||'—')}</div></div><div><label>Guardian phone</label><div>${esc(p.parent_phone||'—')}</div></div><div class="full"><label>Emergency contact</label><div>${esc(p.emergency_contact||'—')}</div></div></div></div><div class="card"><div class="sectionhead"><h3>Current subscription</h3>${d.subscriptions[0]?badge(d.subscriptions[0].subscription_status):badge('Pending')}</div>${d.subscriptions[0]?`<div class="subhero"><div><div class="amount">${esc(d.subscriptions[0].plan_name)}</div><div class="sub">${esc(formatDate(d.subscriptions[0].start_date))} → ${esc(formatDate(d.subscriptions[0].expiry_date))}</div></div><div style="text-align:right"><div class="amount">${esc(money(d.subscriptions[0].amount))}</div><div>${paymentBadge(d.subscriptions[0].payment_status)}</div></div></div><button class="primary renew" onclick="openRenewModal(${d.subscriptions[0].id},${p.id})">Renew subscription</button><button class="secondary renew" onclick="sendRenewalReminder(${p.id})">Send renewal reminder</button>`:'<div class="empty">No subscription on file.</div>'}</div><div class="card"><div class="sectionhead"><h3>Attendance history</h3><span class="sub">Last 30 records</span></div>${d.attendance.length?`<table class="table"><thead><tr><th>Date</th><th>Status</th></tr></thead><tbody>${d.attendance.map(a=>`<tr><td>${esc(formatDate(a.attendance_date))}</td><td>${badge(a.status)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No attendance recorded yet.</div>'}</div><div class="card"><div class="sectionhead"><h3>Staff notes</h3><button class="secondary" onclick="openNoteModal(${p.id})">＋ Add note</button></div>${d.notes.length?d.notes.map(n=>`<div style="padding:10px 0;border-bottom:1px solid var(--line);font-size:13px">${esc(n.note)}<div class="sub" style="margin-top:4px">${formatDate(n.created_at)}</div></div>`).join(''):'<div class="empty">No notes yet.</div>'}</div></div>`}catch(e){toast(e.message)}}

async function loadSubs(){let d=await api('subscriptions');subs=d.subscriptions;renderSubs()}
function renderSubs(){let s=subs.filter(x=>(!subFilter.value||x.subscription_status===subFilter.value)&&(!subSearch.value||`${x.first_name} ${x.last_name} ${x.plan_name}`.toLowerCase().includes(subSearch.value.toLowerCase())));subsBody.innerHTML=s.map(x=>`<tr><td><div class="person"><div class="mini">${initials(x)}</div><b>${esc(x.first_name+' '+x.last_name)}</b></div></td><td>${esc(x.plan_name)}</td><td>${esc(formatDate(x.start_date))}</td><td>${esc(formatDate(x.expiry_date))}</td><td>${esc(money(x.amount))}</td><td>${paymentBadge(x.payment_status)}</td><td>${badge(x.subscription_status)}</td><td>${x.subscription_status!=='Active'?`<button class="primary" style="padding:7px 10px;font-size:11px" onclick="openRenewModal(${x.id},${x.player_id})">Renew</button>`:'<span class="sub">Up to date</span>'}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">No subscriptions found.</td></tr>'}

async function loadAttendance(){let d=await api('attendance',{query:'&date='+encodeURIComponent(attDate.value)+'&category='+encodeURIComponent(attCategory.value)});attendanceList.innerHTML=d.players.map(p=>`<div style="display:flex;align-items:center;justify-content:space-between;padding:12px 4px;border-bottom:1px solid var(--line)"><div class="person"><div class="mini">${avatar(p)}</div><div><b>${esc(p.first_name+' '+p.last_name)}</b><div class="sub">${sportIcon(p.sport)} ${esc(p.sport)} · ${esc(p.category)}</div></div></div><div style="display:flex;gap:6px"><button class="${p.attendance_status==='Present'?'primary':'secondary'} attbtn" data-id="${p.id}" data-status="Present" onclick="toggleAtt(this)">Present</button><button class="${p.attendance_status==='Absent'?'danger':'secondary'} attbtn" data-id="${p.id}" data-status="Absent" onclick="toggleAtt(this)">Absent</button></div></div>`).join('')||'<div class="empty">No active players in this category.</div>'}
function toggleAtt(btn){let row=btn.parentElement;row.querySelectorAll('button').forEach(b=>b.className='secondary attbtn');btn.className=btn.dataset.status==='Present'?'primary attbtn':'danger attbtn'}
async function saveAttendance(){let btns=[...document.querySelectorAll('.attbtn')];let groups={};btns.forEach(b=>groups[b.dataset.id]??=b.dataset.status);for(let id in groups){let pair=btns.filter(b=>b.dataset.id===id);let chosen=pair.find(b=>b.classList.contains('primary')||b.classList.contains('danger'));await api('attendance',{method:'POST',body:{player_id:id,attendance_date:attDate.value,status:chosen?.dataset.status||'Absent'}})}toast('Attendance saved successfully');loadDashboard()}

async function loadNotifications(){let d=await api('notifications');notificationsList.innerHTML=d.notifications.map(n=>`<div style="padding:15px 4px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:15px"><div><b>${esc(n.first_name+' '+n.last_name)}</b><div class="sub" style="margin-top:4px">${esc(n.message)}</div></div>${badge(n.status)}</div>`).join('')||'<div class="empty">No reminders yet.</div>'}
async function loadSettings(){let d=await api('settings'),s=d.settings;settingsForm.innerHTML=`<div class="field"><label>Academy name</label><input id="setName" value="${esc(s.academy_name)}"></div><div class="field"><label>Phone</label><input id="setPhone" value="${esc(s.phone||'')}"></div><div class="field"><label>Email</label><input id="setEmail" value="${esc(s.email||'')}"></div><div class="field"><label>Location</label><input id="setLocation" value="${esc(s.location||'')}"></div><div class="field full"><label>Sports (comma separated)</label><input id="setSports" value="${esc((s.sports||[]).join(', '))}"></div><div class="field full"><label>Teams / categories</label><input id="setCats" value="${esc((s.categories||[]).join(', '))}"></div><input type="hidden" id="setId" value="${s.id}">`}
async function saveSettings(){await api('settings',{method:'PUT',body:{id:setId.value,academy_name:setName.value,phone:setPhone.value,email:setEmail.value,location:setLocation.value,sports:setSports.value.split(',').map(x=>x.trim()).filter(Boolean),categories:setCats.value.split(',').map(x=>x.trim()).filter(Boolean)}});toast('Settings saved')}

function closeModal(){modal.classList.remove('show')}function removePlayerPhoto(){let preview=document.getElementById('photoPreview');if(!preview)return;preview.dataset.removePhoto='true';preview.textContent=preview.dataset.initials||'';let input=document.getElementById('playerPhoto');if(input)input.value=''}function openModal(title,html){modalTitle.textContent=title;modalContent.innerHTML=html;modal.classList.add('show')}
function openPlayerModal(p){p=p||{};openModal(p.id?'Edit player':'Add new player',`<form onsubmit="submitPlayer(event,${p.id||''})"><div class="formgrid"><div class="field full photoField"><label>Player photo</label><div class="photoUpload"><div class="uploadPreview mini" id="photoPreview" data-initials="${esc(initials(p))}" data-remove-photo="false">${avatar(p)}</div><div><input id="playerPhoto" name="photo_file" type="file" accept="image/*">${p.photo_url?'<button type="button" class="secondary" style="margin-top:8px" onclick="removePlayerPhoto()">Remove photo</button>':''}<div class="sub">JPG, PNG or WebP. The image is resized automatically for the academy profile.</div></div></div></div><div class="field"><label>First name</label><input name="first_name" required value="${esc(p.first_name||'')}"></div><div class="field"><label>Last name</label><input name="last_name" required value="${esc(p.last_name||'')}"></div><div class="field"><label>Date of birth</label><input name="date_of_birth" type="date" required value="${esc(p.date_of_birth||'')}"></div><div class="field"><label>Gender</label><select name="gender"><option ${p.gender==='Male'||!p.gender?'selected':''}>Male</option><option ${p.gender==='Female'?'selected':''}>Female</option></select></div><div class="field"><label>Phone</label><input name="phone" value="${esc(p.phone||'')}"></div><div class="field"><label>Parent / guardian</label><input name="parent_name" value="${esc(p.parent_name||'')}"></div><div class="field"><label>Guardian phone</label><input name="parent_phone" value="${esc(p.parent_phone||'')}"></div><div class="field"><label>Emergency contact</label><input name="emergency_contact" value="${esc(p.emergency_contact||'')}"></div><div class="field"><label>Sport</label><select name="sport">${['Football','Basketball','Swimming','Volleyball','Taekwondo'].map(x=>`<option value="${x}" ${p.sport===x?'selected':''}>${sportIcon(x)} ${x}</option>`).join('')}</select></div><div class="field"><label>Category</label><select name="category">${['U10','U12','U14','U16','Senior'].map(x=>`<option ${p.category===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Coach</label><input name="coach" value="${esc(p.coach||'')}"></div><div class="field"><label>Status</label><select name="status"><option>Active</option><option ${p.status==='Inactive'?'selected':''}>Inactive</option></select></div></div><div class="formactions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save player</button></div></form>`)}
async function submitPlayer(e,id){e.preventDefault();try{let b=Object.fromEntries(new FormData(e.currentTarget).entries());const file=b.photo_file;delete b.photo_file;if(document.getElementById('photoPreview')?.dataset.removePhoto==='true')b.remove_photo=true;if(file&&file.size)b.photo_url=await readPhoto(file);if(id){b.id=id;await api('player',{method:'PUT',body:b});toast('Player updated')}else{await api('player',{method:'POST',body:b});toast('Player added')}closeModal();loadPlayers();loadDashboard();}catch(err){toast(err.message)}}

document.addEventListener('change',e=>{if(e.target.id==='playerPhoto'){const file=e.target.files?.[0];if(!file)return;const r=document.getElementById('photoPreview');const reader=new FileReader();reader.onload=()=>{r.dataset.removePhoto='false';r.innerHTML=`<img src="${esc(reader.result)}" alt="Photo preview">`};reader.readAsDataURL(file)}});
function editPlayer(id){let p=players.find(x=>String(x.id)===String(id));openPlayerModal(p)}
async function deletePlayer(id){if(!confirm('Delete this player and their records?'))return;await api('player',{method:'DELETE',query:'&id='+id});toast('Player deleted');loadPlayers();loadDashboard()}

async function openSubModal(){let allPlayers;try{allPlayers=(await api('players')).players}catch(e){return toast(e.message)}openModal('New subscription',`<form onsubmit="submitSub(event)"><div class="formgrid"><div class="field full"><label>Player</label><select name="player_id" required>${allPlayers.map(p=>`<option value="${p.id}">${esc(p.first_name+' '+p.last_name)}</option>`).join('')}</select></div><div class="field"><label>Plan</label><select name="plan_name"><option>Monthly</option><option>3 Months</option><option>6 Months</option><option>Annual</option></select></div><div class="field"><label>Amount</label><input name="amount" type="number" value="35"></div><div class="field"><label>Start date</label><input name="start_date" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Expiry date</label><input name="expiry_date" type="date" required></div><div class="field"><label>Payment</label><select name="payment_status"><option>Paid</option><option>Pending</option></select></div></div><div class="formactions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Create subscription</button></div></form>`)}
async function submitSub(e){e.preventDefault();let b=Object.fromEntries(new FormData(e.currentTarget).entries());b.amount=Number(b.amount);await api('subscription',{method:'POST',body:b});closeModal();toast('Subscription created');loadSubs();loadDashboard()}
function openRenewModal(id,pid){openModal('Renew subscription',`<form onsubmit="submitRenew(event,${id},${pid})"><div class="notice">Renewing creates a new subscription record and preserves the player's history.</div><div class="formgrid"><div class="field"><label>Plan</label><select name="plan_name"><option>Monthly</option><option>3 Months</option><option>6 Months</option><option>Annual</option></select></div><div class="field"><label>Months</label><select name="months"><option value="1">1</option><option value="3">3</option><option value="6">6</option><option value="12">12</option></select></div><div class="field"><label>Amount</label><input name="amount" type="number" value="35"></div></div><div class="formactions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Confirm renewal</button></div></form>`)}
async function submitRenew(e,id,pid){e.preventDefault();let b=Object.fromEntries(new FormData(e.currentTarget).entries());b.id=id;b.months=Number(b.months);b.amount=Number(b.amount);b.player_id=pid;await api('renew',{method:'POST',body:b});closeModal();toast('Subscription renewed successfully');loadSubs();loadDashboard();if(String(currentPlayer?.player?.id)===String(pid))viewPlayer(pid)}
function openNoteModal(pid){openModal('Add staff note',`<form onsubmit="submitNote(event,${pid})"><div class="field"><label>Note</label><textarea name="note" required placeholder="Add a short observation or coaching note…"></textarea></div><div class="formactions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save note</button></div></form>`)}
async function submitNote(e,pid){e.preventDefault();let b=Object.fromEntries(new FormData(e.currentTarget).entries());b.player_id=pid;await api('note',{method:'POST',body:b});closeModal();toast('Note added');viewPlayer(pid)}
async function sendRenewalReminder(pid){try{let p=currentPlayer?.player;if(!p||String(p.id)!==String(pid))throw Error('Player details are unavailable.');await api('reminder',{method:'POST',body:{player_id:pid,message:`Please renew the subscription for ${p.first_name} ${p.last_name}.`}});toast('Renewal reminder sent');loadNotifications();loadDashboard()}catch(e){toast(e.message)}}
function toast(msg){let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}

document.getElementById('playerSearch').addEventListener('input',loadPlayers);
document.getElementById('sportFilter').addEventListener('change',loadPlayers);
document.getElementById('statusFilter').addEventListener('change',loadPlayers);
document.getElementById('subSearch').addEventListener('input',renderSubs);
document.getElementById('subFilter').addEventListener('change',renderSubs);
document.getElementById('attDate').addEventListener('change',loadAttendance);
document.getElementById('attCategory').addEventListener('change',loadAttendance);

function boot(){document.getElementById('attDate').value=new Date().toISOString().slice(0,10);loadDashboard();loadPlayers();}
if(token){showApp();boot()}else{showLogin()}
